services:
  - type: web
    name: saas-freelance-frontend
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd frontend && npm ci && npm run build
    startCommand: cd frontend && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NPM_CONFIG_PRODUCTION
        value: false
